### PR TITLE
Quoted cookies

### PR DESCRIPTION
**Pull request by bluesmoon**
Add quotes around complex cookies, and remove them when parsing.

### CODE REVIEW

**Comment by bluesmoon** [comment]
@andreas-marschke @nicjansma @cvazac please review

**Comment by nicjansma** [comment]
LGTM

**Comment by cvazac** [comment]
will this work if the cookie value has a double-quote in it?

**Comment by bluesmoon** [comment]
It only replaces a single leading and trailing double quote -- the same quotes that it adds.  Any double quote that was in the cookie would become a `%22` anyway.

**Pull request merged**
